export const ADD_ARCHIVE_LIST = "ADD_ARCHIVE_LIST/LIST_REDUCER";
export const DELETE_LIST = "DELETE_LIST/LIST_REDUCER";
export const ADD_LIST = "ADD_LIST/LIST_REDUCER";

export const EDIT_LIST = "EDIT_LIST/LIST_REDUCER";

export const VISIBILITY_MODAL_WINDOW = "VISIBILITY_MODAL_WINDOW/MODAL_REDUCER";
